services:
  - type: web
    name: phishing-attack-defender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python phishing_ml_model/train_models.py
    startCommand: gunicorn --chdir backend app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
